services:
  xtion-thefool0:
    image: xtion-thefool0:latest
    container_name: xtion-thefool0
    restart: unless-stopped


    ports:
      - "3000:3000"

    env_file:
      - path: .env
        required: false


    networks:
      - app-network

networks:
  app-network:
    driver: bridge


